### ISSUE TITLE
Doesn't work in Cron

### ISSUE THREAD

**Issue by huyz** [danielpunkass/RemindersImport#6]
I can get it to work from the command line, but when in cron, nothing happens and I get no errors or logs. Any ideas?

**Comment by danielpunkass** [comment]
I have also switched to using a launch agent and I think this is the canonical approach going forward. As detailed in #8, you may also need to do a one-time run of the tool manually in order to approve the required permissions for it to be able to access your Reminders, and to "control OmniFocus".
